version: "3.7"

services:
  server:
    container_name: express-setup-api
    restart: always
    build: .
    ports:
      - 3333:${PORT}
    links:
      - database
    volumes:
      - .:/usr/src/app
  
  database:
    container_name: express-setup-database
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports:
      - 3306:${DATABASE_PORT}
    logging:
      driver: none
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
